/****************************************************************************************************
Desarrollado por:   VASS
Proyecto:           -
Descripción:        Interfaz para las estructuras del body del request de los distintos callouts

Cambios (Versiones)
-----------------------------------------------------------------------------------------------------
No.     Fecha           Autor                   Descripción
-----   ----------      --------------------    -----------------------------------------------------
1.0     2019-10-01		Jorge Levenfeld			Creación de la Clase.                                       
*/
public interface RequestBody_CLS {
  String serializeRequestBody( RequestBody_CLS requestBody );
}